// AUTO-GENERATED by scripts/generate-routes.mjs — DO NOT EDIT

import Tool0 from "@/tools/base64/page";
import Tool1 from "@/tools/color-converter/page";
import Tool2 from "@/tools/image-converter/page";
import Tool3 from "@/tools/image-palette/page";
import Tool4 from "@/tools/image-resizer/page";
import Tool5 from "@/tools/image-to-base64/page";
import Tool6 from "@/tools/image-watermark/page";
import Tool7 from "@/tools/json-formatter/page";
import Tool8 from "@/tools/password-generator/page";
import Tool9 from "@/tools/qrcode-generator/page";
import Tool10 from "@/tools/summarizer/page";
import Tool11 from "@/tools/text-stats/page";
import Tool12 from "@/tools/translator/page";
import Tool13 from "@/tools/url-parser/page";

export const toolSlugs = ["base64","color-converter","image-converter","image-palette","image-resizer","image-to-base64","image-watermark","json-formatter","password-generator","qrcode-generator","summarizer","text-stats","translator","url-parser"];

export const toolComponents: Record<string, { Component: React.ComponentType }> = {
  "base64": { Component: Tool0 },
  "color-converter": { Component: Tool1 },
  "image-converter": { Component: Tool2 },
  "image-palette": { Component: Tool3 },
  "image-resizer": { Component: Tool4 },
  "image-to-base64": { Component: Tool5 },
  "image-watermark": { Component: Tool6 },
  "json-formatter": { Component: Tool7 },
  "password-generator": { Component: Tool8 },
  "qrcode-generator": { Component: Tool9 },
  "summarizer": { Component: Tool10 },
  "text-stats": { Component: Tool11 },
  "translator": { Component: Tool12 },
  "url-parser": { Component: Tool13 },
};
