// AUTO-GENERATED by scripts/generate-routes.mjs — DO NOT EDIT
// Overwrites lib/tools.ts during build.

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  tags: string[];
  ai: boolean;
  category: string;
}

export function getTools(): ToolMeta[] {
  return [
  {
    "slug": "base64",
    "name": "BASE64 ENCODER",
    "description": "Encode and decode Base64 text",
    "tags": [
      "data",
      "encode"
    ],
    "ai": false,
    "category": "encode"
  },
  {
    "slug": "color-converter",
    "name": "颜色转换器",
    "description": "颜色值互转，取色器，多格式显示",
    "tags": [
      "color",
      "design"
    ],
    "ai": false,
    "category": "color"
  },
  {
    "slug": "image-converter",
    "name": "图片格式互转",
    "description": "PNG/JPEG/WebP/SVG 互转，支持 SVG→栅格",
    "tags": [
      "image",
      "convert"
    ],
    "ai": false,
    "category": "image"
  },
  {
    "slug": "image-palette",
    "name": "图片取色器",
    "description": "从图片提取主色调和调色板",
    "tags": [
      "image",
      "color"
    ],
    "ai": false,
    "category": "image"
  },
  {
    "slug": "image-resizer",
    "name": "图片缩放",
    "description": "按像素尺寸或文件大小调整图片",
    "tags": [
      "image",
      "resize"
    ],
    "ai": false,
    "category": "image"
  },
  {
    "slug": "image-to-base64",
    "name": "图片转 Base64",
    "description": "图片转 Base64 编码，用于内嵌 HTML",
    "tags": [
      "image",
      "base64"
    ],
    "ai": false,
    "category": "image"
  },
  {
    "slug": "image-watermark",
    "name": "图片水印",
    "description": "图片添加文字水印或图片水印，可调位置/透明度/大小",
    "tags": [
      "image",
      "watermark"
    ],
    "ai": false,
    "category": "image"
  },
  {
    "slug": "json-formatter",
    "name": "JSON FORMATTER",
    "description": "Format, validate and minify JSON",
    "tags": [
      "data",
      "format"
    ],
    "ai": false,
    "category": "data"
  },
  {
    "slug": "password-generator",
    "name": "随机码生成器",
    "description": "生成随机密码/密钥，控制长度和字符类型",
    "tags": [
      "security",
      "generate"
    ],
    "ai": false,
    "category": "security"
  },
  {
    "slug": "qrcode-generator",
    "name": "二维码生成器",
    "description": "将网址/文本转为二维码，可调整大小下载",
    "tags": [
      "image",
      "encoding"
    ],
    "ai": false,
    "category": "encode"
  },
  {
    "slug": "summarizer",
    "name": "摘要总结",
    "description": "输入长文或URL，输出要点摘要",
    "tags": [
      "ai",
      "summary",
      "text"
    ],
    "ai": true,
    "category": "ai"
  },
  {
    "slug": "text-stats",
    "name": "字符统计",
    "description": "统计字数/词数/阅读时间，支持 Markdown",
    "tags": [
      "text",
      "analysis"
    ],
    "ai": false,
    "category": "text"
  },
  {
    "slug": "translator",
    "name": "AI TRANSLATOR",
    "description": "Translate text using AI API",
    "tags": [
      "ai",
      "translate"
    ],
    "ai": true,
    "category": "ai"
  },
  {
    "slug": "url-parser",
    "name": "URL 解析器",
    "description": "解析 URL 协议/域名/路径/参数/哈希",
    "tags": [
      "web",
      "parser"
    ],
    "ai": false,
    "category": "web"
  }
];
}
