import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const toolsDir = path.join(root, "tools");
const outputFile = path.join(root, "lib", "tools-generated.ts");

function scanTools() {
  const slugs = [];
  const entries = fs.readdirSync(toolsDir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const pageFile = path.join(toolsDir, entry.name, "page.tsx");
    if (fs.existsSync(pageFile)) {
      slugs.push(entry.name);
    }
  }

  return slugs;
}

function generate(slugs) {
  const imports = slugs
    .map((s, i) => `import Tool${i} from "@/tools/${s}/page";`)
    .join("\n");

  const entries = slugs
    .map((s, i) => `  "${s}": { Component: Tool${i} },`)
    .join("\n");

  const content = `// AUTO-GENERATED by scripts/generate-routes.mjs — DO NOT EDIT

${imports}

export const toolSlugs = ${JSON.stringify(slugs)};

export const toolComponents: Record<string, { Component: React.ComponentType }> = {
${entries}
};
`;

  fs.writeFileSync(outputFile, content, "utf-8");
  console.log(`[generate-routes] Generated tool map with ${slugs.length} tools: ${slugs.join(", ")}`);
}

const slugs = scanTools();
generate(slugs);

// Also update lib/tools.ts with the real tool list
const toolMetas = [];
for (const slug of slugs) {
  const metaPath = path.join(toolsDir, slug, "meta.json");
  if (fs.existsSync(metaPath)) {
    const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8"));
    toolMetas.push({ slug, ...meta });
  }
}

const toolsTs = `// AUTO-GENERATED by scripts/generate-routes.mjs — DO NOT EDIT
// Overwrites lib/tools.ts during build.

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  tags: string[];
  ai: boolean;
  category: string;
}

export function getTools(): ToolMeta[] {
  return ${JSON.stringify(toolMetas, null, 2)};
}
`;

fs.writeFileSync(path.join(root, "lib", "tools.ts"), toolsTs, "utf-8");
console.log("[generate-routes] Updated lib/tools.ts");
